"""Command metadata catalog for every canonical command and alias.

Define metadata for every canonical command and alias.
Expose inventory to ``commands``, ``help``, tests, and generated docs.
"""

from __future__ import annotations

from ledgercore.cli import CommandInventory, CommandMetadata

# ── Root commands ──────────────────────────────────────────────────────────

CATALOG_ENTRIES: tuple[CommandMetadata, ...] = (
    CommandMetadata(
        path="init",
        summary="Initialize a new Memoryledger project in the current directory.",
        audience="both",
        stability="stable",
        effect="workspace-write",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="status",
        summary="Show project status (initialized, memory counts, migration state).",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="info",
        summary="Show full read-only project inventory.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="doctor",
        summary="Run read-only diagnostics on project health.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="next-action",
        summary="Return the recommended next workflow action.",
        audience="agent",
        stability="beta",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="commands",
        summary="List all registered commands with metadata.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="help",
        summary="Show nested help for a command path.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="preview",
        summary="Render without modifying authoritative or derived state.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="build",
        summary="Materialize deterministic derived artifacts in the artifacts mount.",
        audience="both",
        stability="stable",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="export",
        summary="Write selected generated artifacts to user/workspace destinations.",
        audience="both",
        stability="stable",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="finalize",
        summary="Accept all candidates, build, and export in one orchestrated workflow.",
        audience="agent",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Config ─────────────────────────────────────────────────────────────
    CommandMetadata(
        path="config show",
        summary="Show effective configuration with source tracking.",
        audience="both",
        stability="beta",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="config validate",
        summary="Validate configuration without writing.",
        audience="both",
        stability="beta",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Schema ─────────────────────────────────────────────────────────────
    CommandMetadata(
        path="schema list",
        summary="List available schema names.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="schema show",
        summary="Show field definitions for a schema.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="schema values",
        summary="Show allowed enum values.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    # ── Memory ─────────────────────────────────────────────────────────────
    CommandMetadata(
        path="memory create",
        summary="Create a new memory record.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory list",
        summary="List memory records, optionally filtered.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory show",
        summary="Show one memory record.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory update",
        summary="Replace the body of a memory record.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
        aliases=("memory edit",),
    ),
    CommandMetadata(
        path="memory append",
        summary="Append text to the body of a memory record.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory set-status",
        summary="Change the lifecycle status of one memory.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
        aliases=("memory status",),
    ),
    CommandMetadata(
        path="memory archive",
        summary="Archive a memory record (convenience wrapper for set-status archived).",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory validate",
        summary="Validate a memory record against all guardrails.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory evidence list",
        summary="List evidence references attached to a memory.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    CommandMetadata(
        path="memory evidence add",
        summary="Add an evidence reference to a memory.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    # ── Review ─────────────────────────────────────────────────────────────
    CommandMetadata(
        path="review list",
        summary="List candidate memories awaiting review.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="review accept",
        summary="Accept one or all candidate memories.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    CommandMetadata(
        path="review reject",
        summary="Reject one or all candidate memories.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
    ),
    # ── Evidence ───────────────────────────────────────────────────────────
    CommandMetadata(
        path="evidence scan",
        summary="Scan repository evidence and propose candidate memories.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Import ─────────────────────────────────────────────────────────────
    CommandMetadata(
        path="import text",
        summary="Import memory candidates from text input.",
        audience="agent",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="import run-html",
        summary="Import memory candidates from run HTML logs.",
        audience="agent",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="import current-run",
        summary="Import memory candidates from the current agent run.",
        audience="agent",
        stability="beta",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Agents ─────────────────────────────────────────────────────────────
    CommandMetadata(
        path="agents plan",
        summary="Print the canonical agent workflow commands.",
        audience="agent",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="agents adopt",
        summary="Adopt an existing AGENTS.md into memory records.",
        audience="agent",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="agents verify-adoption",
        summary="Verify that adopted memories match a source AGENTS.md.",
        audience="agent",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Template ───────────────────────────────────────────────────────────
    CommandMetadata(
        path="template list",
        summary="List available global templates.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="template show",
        summary="Show one template's content.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="template apply",
        summary="Apply a template to create or update a memory.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="template sync",
        summary="Sync a template (apply with optional acceptance).",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="template remove",
        summary="Remove a template-backed memory.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Storage ────────────────────────────────────────────────────────────
    CommandMetadata(
        path="storage where",
        summary="Show complete storage topology information.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="storage validate",
        summary="Validate storage layout and bindings (read-only).",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
        aliases=("storage verify",),
    ),
    CommandMetadata(
        path="storage set",
        summary="Set a mount's storage kind and scope.",
        audience="both",
        stability="beta",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="storage clear-override",
        summary="Remove a local mount override.",
        audience="both",
        stability="beta",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Migrate ────────────────────────────────────────────────────────────
    CommandMetadata(
        path="migrate status",
        summary="Show migration status for all registered migrations.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="migrate plan",
        summary="Generate a read-only migration plan.",
        audience="both",
        stability="stable",
        effect="read",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="migrate apply",
        summary="Apply a migration plan.",
        audience="both",
        stability="stable",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="migrate recover",
        summary="Recover from a migration journal.",
        audience="both",
        stability="beta",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    CommandMetadata(
        path="migrate cleanup",
        summary="Clean up legacy paths after successful migration.",
        audience="both",
        stability="beta",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
    ),
    # ── Deprecated aliases ─────────────────────────────────────────────────
    CommandMetadata(
        path="memory status",
        summary="Deprecated alias for memory set-status.",
        audience="both",
        stability="deprecated",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
        deprecated=True,
        replacement="memory set-status",
    ),
    CommandMetadata(
        path="memory edit",
        summary="Deprecated alias for memory update.",
        audience="both",
        stability="deprecated",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
        deprecated=True,
        replacement="memory update",
    ),
    CommandMetadata(
        path="review archive",
        summary="Deprecated alias for memory archive.",
        audience="both",
        stability="deprecated",
        effect="ledger-write",
        requires_workspace=True,
        targeting="memory-ref",
        supports_json=True,
        deprecated=True,
        replacement="memory archive",
    ),
    CommandMetadata(
        path="storage verify",
        summary="Deprecated alias for storage validate.",
        audience="both",
        stability="deprecated",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="storage validate",
    ),
    CommandMetadata(
        path="render",
        summary="Deprecated alias for build.",
        audience="both",
        stability="deprecated",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="build",
    ),
    CommandMetadata(
        path="agents render",
        summary="Deprecated alias for build.",
        audience="agent",
        stability="deprecated",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="build",
    ),
    CommandMetadata(
        path="agents export",
        summary="Deprecated alias for export.",
        audience="agent",
        stability="deprecated",
        effect="workspace-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="export",
    ),
    CommandMetadata(
        path="templates list",
        summary="Deprecated alias for template list.",
        audience="both",
        stability="deprecated",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="template list",
    ),
    CommandMetadata(
        path="templates show",
        summary="Deprecated alias for template show.",
        audience="both",
        stability="deprecated",
        effect="read",
        requires_workspace=False,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="template show",
    ),
    CommandMetadata(
        path="templates apply",
        summary="Deprecated alias for template apply.",
        audience="both",
        stability="deprecated",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="template apply",
    ),
    CommandMetadata(
        path="templates sync",
        summary="Deprecated alias for template sync.",
        audience="both",
        stability="deprecated",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="template sync",
    ),
    CommandMetadata(
        path="templates remove",
        summary="Deprecated alias for template remove.",
        audience="both",
        stability="deprecated",
        effect="ledger-write",
        requires_workspace=True,
        targeting="none",
        supports_json=True,
        deprecated=True,
        replacement="template remove",
    ),
)

CATALOG = CommandInventory(CATALOG_ENTRIES)
