from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path

KINDS = ("rule", "learning", "episode", "procedure", "semantic", "document", "local")
STATUSES = ("candidate", "accepted", "rejected", "archived")
SCOPES = ("global", "repo", "directory", "file", "command", "workflow", "local")
RENDER_TARGETS = ("root_agents", "linked_doc", "nested_agents", "none")
EVIDENCE_KINDS = (
    "file",
    "config",
    "run",
    "command",
    "user_approval",
    "external",
)
GENERATED_MARKER = "<!-- Generated by memoryledger. Do not edit directly. -->"


@dataclass(frozen=True)
class EvidenceRef:
    kind: str
    title: str
    uri: str
    excerpt: str = ""
    content_hash: str = ""
    line_start: int | None = None
    line_end: int | None = None
    timestamp: str = ""

    def to_dict(self) -> dict[str, object]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> EvidenceRef:
        return cls(
            kind=str(data["kind"]),
            title=str(data["title"]),
            uri=str(data["uri"]),
            excerpt=str(data.get("excerpt", "")),
            content_hash=str(data.get("content_hash", "")),
            line_start=(
                int(str(data["line_start"])) if data.get("line_start") else None
            ),
            line_end=int(str(data["line_end"])) if data.get("line_end") else None,
            timestamp=str(data.get("timestamp", "")),
        )


@dataclass(frozen=True)
class Memory:
    id: str
    kind: str
    title: str
    status: str
    priority: int
    scope: str
    scope_path: str
    render_target: str
    source: str
    created_at: str
    updated_at: str
    version: int
    tags: list[str] = field(default_factory=list)
    origin: str = ""
    origin_hash: str = ""
    section: str = ""
    evidence_refs: list[EvidenceRef] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> Memory:
        raw_tags = data.get("tags", [])
        tags = raw_tags if isinstance(raw_tags, list) else []
        raw_refs = data.get("evidence_refs", [])
        refs = raw_refs if isinstance(raw_refs, list) else []
        return cls(
            id=str(data["id"]),
            kind=str(data["kind"]),
            title=str(data["title"]),
            status=str(data["status"]),
            priority=int(str(data.get("priority", 100))),
            scope=str(data.get("scope", "global")),
            scope_path=str(data.get("scope_path", "")),
            render_target=str(data.get("render_target", "root_agents")),
            source=str(data.get("source", "cli")),
            created_at=str(data["created_at"]),
            updated_at=str(data["updated_at"]),
            version=int(str(data.get("version", 1))),
            tags=[str(tag) for tag in tags],
            origin=str(data.get("origin", "")),
            origin_hash=str(data.get("origin_hash", "")),
            section=str(data.get("section", "")),
            evidence_refs=[
                EvidenceRef.from_dict(ref) for ref in refs if isinstance(ref, dict)
            ],
        )


@dataclass(frozen=True)
class RenderConfig:
    root_agents_path: str = "AGENTS.md"
    linked_docs_dir: str = "docs/agents"
    nested_agents_enabled: bool = False
    linked_docs_enabled: bool = True
    max_root_agents_chars: int = 12000
    max_linked_doc_chars: int = 50000
    include_local: bool = False
    include_rejected: bool = False
    include_evidence: bool = False
    evidence_index_path: str = ""
    sort_order: list[str] = field(
        default_factory=lambda: [
            "rule",
            "procedure",
            "semantic",
            "learning",
            "episode",
            "document",
        ]
    )


@dataclass(frozen=True)
class Template:
    id: str
    version: str
    kind: str
    title: str
    content: str = ""
    content_file: str = ""
    scope: str = "global"
    scope_path: str = ""
    render_target: str = "root_agents"
    section: str = ""
    source_root: Path = Path(".")


@dataclass(frozen=True)
class TemplatePolicy:
    enabled: bool = False
    ids: list[str] = field(default_factory=list)
    auto_accept: bool = False


@dataclass(frozen=True)
class GlobalConfig:
    path: Path
    templates: list[Template] = field(default_factory=list)


@dataclass(frozen=True)
class Config:
    root: Path
    config_path: Path
    ledger_code: str = "ml"
    ledger_name: str = "memoryledger"
    project_name: str = "my-project"
    project_uuid: str = ""
    memoryledger_dir: str = ".memoryledger"
    render: RenderConfig = field(default_factory=RenderConfig)
    allow_run_html: bool = True
    allow_current_run: bool = True
    default_review_status: str = "candidate"
    template_policy: TemplatePolicy = field(default_factory=TemplatePolicy)

    @property
    def storage_dir(self) -> Path:
        return self.root / self.memoryledger_dir
