from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Literal

KINDS = ("rule", "learning", "episode", "procedure", "semantic", "document", "local")
STATUSES = ("candidate", "accepted", "rejected", "archived")
SCOPES = ("global", "repo", "directory", "file", "command", "workflow", "local")
RENDER_TARGETS = ("root_agents", "linked_doc", "nested_agents", "none")
EVIDENCE_KINDS = (
    "file",
    "config",
    "run",
    "command",
    "user_approval",
    "external",
)
GENERATED_MARKER = "<!-- Generated by memoryledger. Do not edit directly. -->"


@dataclass(frozen=True)
class EvidenceRef:
    kind: str
    title: str
    uri: str
    excerpt: str = ""
    content_hash: str = ""
    line_start: int | None = None
    line_end: int | None = None
    timestamp: str = ""

    def to_dict(self) -> dict[str, object]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> EvidenceRef:
        return cls(
            kind=str(data["kind"]),
            title=str(data["title"]),
            uri=str(data["uri"]),
            excerpt=str(data.get("excerpt", "")),
            content_hash=str(data.get("content_hash", "")),
            line_start=(
                int(str(data["line_start"])) if data.get("line_start") else None
            ),
            line_end=int(str(data["line_end"])) if data.get("line_end") else None,
            timestamp=str(data.get("timestamp", "")),
        )


@dataclass(frozen=True)
class Memory:
    id: str
    kind: str
    title: str
    status: str
    priority: int
    scope: str
    scope_path: str
    render_target: str
    source: str
    created_version: int
    modified_version: int
    tags: list[str] = field(default_factory=list)
    origin: str = ""
    origin_hash: str = ""
    section: str = ""
    evidence_refs: list[EvidenceRef] = field(default_factory=list)

    @property
    def version(self) -> int:
        return self.modified_version

    def to_dict(self) -> dict[str, object]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> Memory:
        raw_tags = data.get("tags", [])
        tags = raw_tags if isinstance(raw_tags, list) else []
        raw_refs = data.get("evidence_refs", data.get("evidence", []))
        refs = raw_refs if isinstance(raw_refs, list) else []
        legacy_version = int(str(data.get("version", 1)))
        return cls(
            id=str(data["id"]),
            kind=str(data["kind"]),
            title=str(data["title"]),
            status=str(data["status"]),
            priority=int(str(data.get("priority", 100))),
            scope=str(data.get("scope", "global")),
            scope_path=str(data.get("scope_path", "")),
            render_target=str(data.get("render_target", "root_agents")),
            source=str(data.get("source", "cli")),
            created_version=int(str(data.get("created_version", legacy_version))),
            modified_version=int(str(data.get("modified_version", legacy_version))),
            tags=[str(tag) for tag in tags],
            origin=str(data.get("origin", "")),
            origin_hash=str(data.get("origin_hash", "")),
            section=str(data.get("section", "")),
            evidence_refs=[
                EvidenceRef.from_dict(ref) for ref in refs if isinstance(ref, dict)
            ],
        )


@dataclass(frozen=True)
class RenderConfig:
    root_agents_path: str = "AGENTS.md"
    linked_docs_dir: str = "agent_docs"
    nested_agents_enabled: bool = False
    linked_docs_enabled: bool = True
    max_root_agents_chars: int = 12000
    max_linked_doc_chars: int = 50000
    include_local: bool = False
    include_rejected: bool = False
    include_evidence: bool = False
    evidence_index_path: str = ""
    sort_order: list[str] = field(
        default_factory=lambda: [
            "rule",
            "procedure",
            "semantic",
            "learning",
            "episode",
            "document",
        ]
    )


@dataclass(frozen=True)
class Template:
    id: str
    version: str
    kind: str
    title: str
    content: str = ""
    content_file: str = ""
    scope: str = "global"
    scope_path: str = ""
    render_target: str = "root_agents"
    section: str = ""
    source_root: Path = Path(".")


@dataclass(frozen=True)
class TemplatePolicy:
    enabled: bool = False
    ids: list[str] = field(default_factory=list)
    auto_accept: bool = False


@dataclass(frozen=True)
class GlobalConfig:
    path: Path
    templates: list[Template] = field(default_factory=list)


@dataclass(frozen=True)
class Config:
    root: Path
    config_path: Path
    ledger_code: str = "ml"
    ledger_name: str = "memoryledger"
    project_name: str = "my-project"
    project_uuid: str = ""
    memoryledger_dir: str = ".memoryledger"
    render: RenderConfig = field(default_factory=RenderConfig)
    allow_run_html: bool = True
    allow_current_run: bool = True
    default_review_status: str = "candidate"
    template_policy: TemplatePolicy = field(default_factory=TemplatePolicy)
    artifacts_dir: Path | None = None

    @property
    def storage_dir(self) -> Path:
        return self.root / self.memoryledger_dir


LayoutSource = Literal["canonical", "legacy"]


@dataclass(frozen=True)
class ToolConfig:
    """Project-local settings independent of resolved paths."""

    config_version: int
    ledger_code: str
    ledger_version: int
    render: RenderConfig
    allow_run_html: bool
    allow_current_run: bool
    default_review_status: str
    template_policy: TemplatePolicy


@dataclass(frozen=True)
class WorkspacePaths:
    """Resolved paths for one active Memoryledger layout."""

    project_root: Path
    manifest_path: Path | None
    local_config_path: Path | None
    config_path: Path
    data_dir: Path
    artifacts_dir: Path | None
    config_binding_path: Path | None
    data_binding_path: Path | None
    artifacts_binding_path: Path | None
    layout_source: LayoutSource

    @property
    def storage_dir(self) -> Path:
        return self.data_dir


@dataclass(frozen=True)
class Workspace:
    config: ToolConfig
    paths: WorkspacePaths
    project_name: str
    project_uuid: str


@dataclass(frozen=True)
class StorageDiscovery:
    project_root: Path
    canonical_manifest: Path | None
    canonical_registered: bool
    canonical_config: Path | None
    canonical_data: Path | None
    canonical_populated: bool
    canonical_valid: bool
    legacy_config: Path | None
    legacy_data: Path | None
    legacy_populated: bool
    completed_migration_journal: Path | None
    status: Literal[
        "uninitialized",
        "canonical",
        "legacy",
        "migration-required",
        "ambiguous",
        "incomplete",
        "conflict",
    ]


@dataclass(frozen=True)
class DerivedState:
    ledger_version: int
    next_memory_number: int
    next_import_number: int


@dataclass(frozen=True)
class LegacyInventory:
    config_path: Path
    data_dir: Path
    memory_ids: tuple[str, ...]
    import_ids: tuple[str, ...]
    regular_files: tuple[Path, ...]
    derived_state: DerivedState
