"""Test export, doctor, and entrypoint alias."""

from __future__ import annotations

import os
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path

from memoryledger.export import render_export
from memoryledger.model import MemoryStatus, MemoryType
from memoryledger.store import init_store

FIXED_NOW = datetime(2026, 6, 13, 10, 0, tzinfo=timezone(timedelta(hours=2)))


def test_export_writes_compact_accepted_references_only(tmp_path: Path) -> None:
    """export --target agents-md writes compact @../memories/... refs for accepted only."""
    store = init_store(tmp_path, now=FIXED_NOW)
    # Accepted procedural.
    mem1 = store.capture_memory(
        memory_type=MemoryType.procedural,
        title="Testing command",
        body="Run pytest.",
    )
    store.set_status(
        mem1.id, MemoryStatus.accepted, event_type="memory.accepted", actor="user"
    )
    # Candidate (not accepted) — should NOT appear in export.
    store.capture_memory(
        memory_type=MemoryType.semantic,
        title="Unaccepted fact",
        body="Not yet accepted.",
    )
    # Local — should NOT appear in export.
    store.capture_memory(
        memory_type=MemoryType.local,
        title="Local note",
        body="Private.",
    )
    # Accepted rule.
    mem_rule = store.capture_memory(
        memory_type=MemoryType.rule,
        title="Linting rule",
        body="Always lint.",
    )
    store.set_status(
        mem_rule.id, MemoryStatus.accepted, event_type="memory.accepted", actor="user"
    )

    text = render_export(list(store.iter_memories()), state_dir=store.state_dir)
    assert "# Project Memory" in text
    assert "Generated by memoryledger" in text
    # Accepted procedural and rule appear.
    assert "@../memories/procedures/mem-20260613-0001.md" in text
    assert "@../memories/rules/mem-20260613-0004.md" in text
    # Candidate and local do not.
    assert "Unaccepted fact" not in text
    assert "Local note" not in text
    # No content other than references.
    assert "Run pytest." not in text


def test_export_atomic_write(tmp_path: Path) -> None:
    """export writes the file atomically to the export path."""
    store = init_store(tmp_path, now=FIXED_NOW)
    mem = store.capture_memory(
        memory_type=MemoryType.procedural,
        title="Test",
        body="Body.",
    )
    store.set_status(
        mem.id, MemoryStatus.accepted, event_type="memory.accepted", actor="user"
    )
    from memoryledger.config import ExportTarget
    from memoryledger.export import write_export

    out = store.exports_dir / "AGENTS.memory.md"
    write_export(
        list(store.iter_memories()),
        target=ExportTarget.agents_md,
        output_path=out,
        state_dir=store.state_dir,
    )
    assert out.exists()
    assert "@../memories/" in out.read_text(encoding="utf-8")


def test_doctor_reports_malformed_jsonl(tmp_path: Path) -> None:
    """doctor reports malformed JSONL rows without crashing."""
    store = init_store(tmp_path, now=FIXED_NOW)
    # Write a malformed line into ledger.jsonl.
    with store.ledger_path.open("a", encoding="utf-8") as fh:
        fh.write("this is not valid json\n")
    report = store.diagnose(create_export_dir=True)
    assert not report.ledger_ok, "ledger should report issues for malformed rows"
    assert len(report.ledger_issues) >= 1
    # But the report object is still usable — no crash.
    assert isinstance(report.all_issues, list)
    assert report.event_count == 0  # only the malformed line exists, no valid events


def test_doctor_reports_missing_front_matter(tmp_path: Path) -> None:
    """doctor reports memory files with missing required front matter fields."""
    store = init_store(tmp_path, now=FIXED_NOW)
    # Drop a memory file with minimal front matter.
    bad_file = store.memories_dir / "procedures" / "bad-memory.md"
    bad_file.write_text(
        "---\nid: mem-20260613-9999\n---\nMissing most fields.\n", encoding="utf-8"
    )
    report = store.diagnose()
    assert not report.memory_files_ok
    assert len(report.front_matter_issues) >= 1
    assert any(
        "missing" in str(i).lower() or "type" in str(i).lower()
        for i in report.front_matter_issues
    ), f"unexpected issues: {report.front_matter_issues}"


def test_doctor_ok_on_clean_project(tmp_path: Path) -> None:
    """doctor reports ok on a clean project with accepted memories."""
    store = init_store(tmp_path, now=FIXED_NOW)
    mem = store.capture_memory(
        memory_type=MemoryType.semantic,
        title="Fact",
        body="Content.",
    )
    store.set_status(
        mem.id, MemoryStatus.accepted, event_type="memory.accepted", actor="user"
    )
    report = store.diagnose()
    assert report.ok
    assert report.all_issues == []


def _run_cli(
    tmp_path: Path, args: list[str], *, env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    """Run the memoryledger CLI as a subprocess in tmp_path."""
    env_vars = dict(os.environ)
    env_vars.pop("MEMORYLEDGER_ACTOR", None)
    env_vars.pop("MEMORYLEDGER_NOW", None)
    env_vars.update(env or {})
    env_vars["MEMORYLEDGER_NOW"] = "2026-06-13T10:00:00+02:00"
    result = subprocess.run(
        ["memoryledger", *args],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        env=env_vars,
    )
    return result


def test_entrypoint_alias_memledger(tmp_path: Path) -> None:
    """Both memoryledger and memledger console_scripts invoke the Typer app."""
    # Set up a project.
    result = _run_cli(tmp_path, ["init"])
    assert result.returncode == 0, f"init failed: {result.stderr}"
    note = tmp_path / "note.md"
    note.write_text("Run pytest.\n")
    result = _run_cli(
        tmp_path,
        ["capture", "--type", "procedural", "--title", "Test", "--body", str(note)],
    )
    assert result.returncode == 0, f"capture failed: {result.stderr}"

    # Now test memledger alias.
    result2 = subprocess.run(
        ["memledger", "list"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        env={**os.environ, "MEMORYLEDGER_NOW": "2026-06-13T10:00:00+02:00"},
    )
    assert result2.returncode == 0, f"memledger list failed: {result2.stderr}"
    assert "mem-20260613-0001" in result2.stdout


def test_doctor_creates_export_dir(tmp_path: Path) -> None:
    """doctor creates the export directory if missing and create_export_dir=True."""
    store = init_store(tmp_path, now=FIXED_NOW)
    # Remove the export dir.
    import shutil

    if store.exports_dir.exists():
        shutil.rmtree(store.exports_dir)
    assert not store.exports_dir.exists()
    report = store.diagnose(create_export_dir=True)
    assert store.exports_dir.exists(), "doctor should create missing export dir"
    assert report.export_dir_created
    assert report.export_dir_ok
