from __future__ import annotations

from .conftest import invoke_ok


def test_render_includes_accepted_only(runner, work) -> None:
    invoke_ok(runner, ["init"])
    invoke_ok(
        runner,
        [
            "memory",
            "create",
            "--kind",
            "rule",
            "--title",
            "A",
            "--text",
            "Accepted rule.",
        ],
    )
    invoke_ok(runner, ["review", "accept", "memory-0001", "--reason", "Approved."])
    invoke_ok(
        runner,
        [
            "memory",
            "create",
            "--kind",
            "rule",
            "--title",
            "C",
            "--text",
            "Candidate rule.",
        ],
    )
    out = invoke_ok(runner, ["render", "--print"]).output
    assert "Accepted rule" in out
    assert "Candidate rule" not in out
    assert "Generated by memoryledger" in out
    assert "Source: memoryledger records" in out


def test_explicit_sections_group_deterministically(runner, work) -> None:
    invoke_ok(runner, ["init"])
    invoke_ok(
        runner,
        [
            "memory",
            "create",
            "--kind",
            "rule",
            "--title",
            "A",
            "--text",
            "Accepted rule.",
            "--section",
            "Build",
        ],
    )
    invoke_ok(runner, ["review", "accept", "memory-0001", "--reason", "Approved."])
    out = invoke_ok(runner, ["render", "--print"]).output
    assert "### Build" in out
