from __future__ import annotations

import json
from pathlib import Path

import yaml

from .conftest import invoke_ok


def _frontmatter(path: Path) -> dict[str, object]:
    return yaml.safe_load(path.read_text().split("---", 2)[1])


def test_storage_v2_create_writes_single_frontmatter_markdown(
    runner, work: Path
) -> None:
    invoke_ok(runner, ["init"])
    invoke_ok(
        runner,
        ["memory", "create", "--kind", "rule", "--title", "R", "--text", "Rule."],
    )

    memory_file = work / ".memoryledger/memories/memory-0001.md"
    assert memory_file.exists()
    assert not (work / ".memoryledger/memories/memory-0001").exists()
    data = _frontmatter(memory_file)
    assert data["created_version"] == 1
    assert data["modified_version"] == 1
    assert "created_at" not in data
    assert "updated_at" not in data
    assert "version" not in data


def test_global_version_increments_once_per_mutation(runner, work: Path) -> None:
    invoke_ok(runner, ["init"])
    invoke_ok(
        runner,
        ["memory", "create", "--kind", "rule", "--title", "R", "--text", "Rule."],
    )
    invoke_ok(
        runner,
        ["memory", "append", "memory-0001", "--text", "More.", "--reason", "Update."],
    )

    config = work / "memoryledger.toml"
    assert "version = 2" in config.read_text()
    data = _frontmatter(work / ".memoryledger/memories/memory-0001.md")
    assert data["created_version"] == 1
    assert data["modified_version"] == 2


def test_storage_v2_migration_removes_sidecars_and_versions(runner, work: Path) -> None:
    invoke_ok(runner, ["init"])
    legacy = work / ".memoryledger/memories/memory-0001"
    (legacy / "versions").mkdir(parents=True)
    (legacy / "memory.yaml").write_text(
        "id: memory-0001\nkind: rule\ntitle: R\nstatus: candidate\npriority: 100\nscope: global\nscope_path: ''\nrender_target: root_agents\nsource: cli\ncreated_at: old\nupdated_at: old\nversion: 7\ntags: []\n"
    )
    (legacy / "content.md").write_text("Rule.\n")
    (legacy / "evidence.md").write_text("")
    (legacy / "versions/v0007.yaml").write_text("{}")

    plan = json.loads(
        invoke_ok(runner, ["migrate", "storage-v2", "--plan", "--json"]).output
    )
    assert plan["legacy_memories"] == ["memory-0001"]
    result = json.loads(
        invoke_ok(runner, ["migrate", "storage-v2", "--apply", "--json"]).output
    )
    assert "memory-0001" in result["legacy_memories"]
    assert (work / ".memoryledger/memories/memory-0001.md").exists()
    assert not legacy.exists()


def test_linked_docs_dir_migration_moves_only_generated_files(
    runner, work: Path
) -> None:
    invoke_ok(runner, ["init"])
    src = work / "docs/agents"
    src.mkdir(parents=True)
    (src / "procedures.md").write_text(
        "<!-- Generated by memoryledger. Do not edit directly. -->\n"
    )
    (src / "manual.md").write_text("manual\n")

    data = json.loads(
        invoke_ok(runner, ["migrate", "linked-docs-dir", "--apply", "--json"]).output
    )
    assert data["move"] == ["docs/agents/procedures.md"]
    assert data["skip"] == ["docs/agents/manual.md"]
    assert (work / "agent_docs/procedures.md").exists()
    assert (src / "manual.md").exists()


def test_finalize_accepts_renders_exports_json(runner, work: Path) -> None:
    invoke_ok(runner, ["init"])
    invoke_ok(
        runner,
        ["memory", "create", "--kind", "rule", "--title", "R", "--text", "Rule."],
    )

    data = json.loads(
        invoke_ok(
            runner,
            ["finalize", "--accept-all", "--reason", "Approved.", "--export", "--json"],
        ).output
    )
    assert data["accepted"] == ["memory-0001"]
    assert data["steps"] == ["accept", "render", "export"]
    assert (work / "AGENTS.md").exists()
    shown = json.loads(
        invoke_ok(runner, ["memory", "show", "memory-0001", "--json"]).output
    )
    assert shown["status"] == "accepted"
