from __future__ import annotations

import json

import yaml

from .conftest import invoke_ok


def test_adopt_preview_is_read_only_and_apply_requires_backup(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    original = "# Agent notes\n\n## Local guidance\n\nKeep this."
    target.write_text(original)
    preview = json.loads(invoke_ok(runner, ["agents", "adopt", "--json"]).output)
    assert preview["mutated"] is False
    assert target.read_text() == original
    assert not list((work / ".ledger/memoryledger/data/memories").iterdir())
    refused = runner.invoke(
        __import__("memoryledger.cli", fromlist=["app"]).app,
        ["agents", "adopt", "--apply"],
    )
    assert refused.exit_code == 1
    assert "ADOPTION_BACKUP_REQUIRED" in refused.output


def test_adopt_backup_accept_and_retry_deduplicate(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    target.write_text("# Notes\n\n## Guidance\n\nKeep this.")
    result = json.loads(
        invoke_ok(
            runner,
            [
                "agents",
                "adopt",
                "--apply",
                "--backup",
                "--accept",
                "--reason",
                "User approved adoption.",
                "--json",
            ],
        ).output
    )
    assert result["candidates"] == ["memory-0001"]
    assert "Generated by memoryledger" in target.read_text()
    assert (work / "AGENTS.md.memoryledger-adopt-1.bak").exists()
    evidence = yaml.safe_load(
        (work / ".ledger/memoryledger/data/memories/memory-0001.md")
        .read_text()
        .split("---", 2)[1]
    )
    assert evidence["evidence"][0]["uri"] == "AGENTS.md"


def test_adopt_apply_exports_linked_docs_when_needed(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    target.write_text("# Notes\n\n## Guidance\n\n" + ("Keep this.\n" * 120))
    invoke_ok(
        runner,
        [
            "agents",
            "adopt",
            "--apply",
            "--backup",
            "--accept",
            "--reason",
            "User approved adoption.",
        ],
    )
    linked = work / "agent_docs" / "documents.md"
    assert linked.exists()
    assert "Guidance" in linked.read_text()


def test_adopt_prevalidates_every_proposal(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    original = (
        "# Notes\n\n## Safe\n\nKeep this.\n\n## Unsafe\n\npassword = abcdefghijklmnop"
    )
    target.write_text(original)
    result = runner.invoke(
        __import__("memoryledger.cli", fromlist=["app"]).app,
        ["agents", "adopt", "--apply", "--backup"],
    )
    assert result.exit_code == 1
    assert target.read_text() == original
    assert not list((work / ".ledger/memoryledger/data/memories").iterdir())


def test_adopt_preview_reports_headings_and_shrink(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    target.write_text("# Notes\n\n## Guidance\n\nKeep this.")
    data = json.loads(invoke_ok(runner, ["agents", "adopt", "--json"]).output)
    assert data["headings"] == ["Notes", "Guidance"]
    assert data["root_expected_to_shrink"] is True
    assert data["proposals"][0]["origin"].endswith(":full-source")


def test_verify_adoption_requires_reachable_full_source(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    target.write_text("# Notes\n\n## Guidance\n\nKeep this.")
    invoke_ok(
        runner,
        [
            "agents",
            "adopt",
            "--apply",
            "--backup",
            "--accept",
            "--reason",
            "User approved adoption.",
        ],
    )
    data = json.loads(
        invoke_ok(
            runner,
            [
                "agents",
                "verify-adoption",
                "--source",
                "AGENTS.md.memoryledger-adopt-1.bak",
                "--json",
            ],
        ).output
    )
    assert data["ok"] is True
    assert data["full_document_reachable"] is True
    assert data["missing_headings"] == []
    assert "part of this agent context" in (work / "AGENTS.md").read_text()
    assert "Full source-preserving copy" in (work / "AGENTS.md").read_text()
