from __future__ import annotations

import json

from .conftest import invoke_ok


def test_adopt_preview_is_read_only_and_apply_requires_backup(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    original = "# Agent notes\n\n## Local guidance\n\nKeep this."
    target.write_text(original)
    preview = json.loads(
        invoke_ok(runner, ["agents", "adopt", "--json"]).output
    )
    assert preview["mutated"] is False
    assert target.read_text() == original
    assert not list((work / ".memoryledger/memories").iterdir())
    refused = runner.invoke(
        __import__("memoryledger.cli", fromlist=["app"]).app,
        ["agents", "adopt", "--apply"],
    )
    assert refused.exit_code == 1
    assert "ADOPTION_BACKUP_REQUIRED" in refused.output


def test_adopt_backup_accept_and_retry_deduplicate(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    target.write_text("# Notes\n\n## Guidance\n\nKeep this.")
    result = json.loads(
        invoke_ok(
            runner,
            [
                "agents",
                "adopt",
                "--apply",
                "--backup",
                "--accept",
                "--reason",
                "User approved adoption.",
                "--json",
            ],
        ).output
    )
    assert result["candidates"] == ["memory-0001"]
    assert "Generated by memoryledger" in target.read_text()
    assert (work / "AGENTS.md.memoryledger-adopt-1.bak").exists()


def test_adopt_prevalidates_every_proposal(runner, work) -> None:
    invoke_ok(runner, ["init"])
    target = work / "AGENTS.md"
    original = (
        "# Notes\n\n## Safe\n\nKeep this.\n\n"
        "## Unsafe\n\npassword = abcdefghijklmnop"
    )
    target.write_text(original)
    result = runner.invoke(
        __import__("memoryledger.cli", fromlist=["app"]).app,
        ["agents", "adopt", "--apply", "--backup"],
    )
    assert result.exit_code == 1
    assert target.read_text() == original
    assert not list((work / ".memoryledger/memories").iterdir())
