"""Memory export for memoryledger.

MVP target: ``agents-md``. The export emits compact modular references
(``@../memories/...``) grouped by memory type, rather than one oversized file.
Only accepted project memory is included; ``local`` memory is excluded by
default.

The export file is written atomically via ``ledgercore.atomic.atomic_write_text``
and an ``memory.exported`` event is appended from the store/CLI layer.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from ledgercore.atomic import atomic_write_text
from ledgercore.io import ensure_dir

from memoryledger.config import ExportTarget
from memoryledger.model import Memory, MemoryStatus, MemoryType
from memoryledger.store import MEMORY_TYPE_FOLDERS

# Display headings and ordered types for the export.
_EXPORT_SECTIONS: tuple[tuple[MemoryType, str], ...] = (
    (MemoryType.rule, "Stable Rules"),
    (MemoryType.procedural, "Procedures"),
    (MemoryType.learning, "Recent Accepted Learnings"),
    (MemoryType.semantic, "Semantic Memory"),
    (MemoryType.episodic, "Episodic Memory"),
)


def accepted_project_memories(memories: list[Memory]) -> list[Memory]:
    """Return only accepted, non-local memories for export."""
    return [
        m
        for m in memories
        if m.status == MemoryStatus.accepted and m.type != MemoryType.local
    ]


def render_export(memories: list[Memory], *, state_dir: Path) -> str:
    """Render the agents-md export text for accepted project memories.

    References are emitted relative to the export directory
    (``<state_dir>/exports/``), so each path looks like
    ``@../memories/<folder>/<id>.md``.
    """
    accepted = accepted_project_memories(memories)
    by_type: dict[MemoryType, list[Memory]] = defaultdict(list)
    for mem in accepted:
        by_type[mem.type].append(mem)

    lines: list[str] = [
        "# Project Memory",
        "",
        "Generated by memoryledger. Do not edit this export directly.",
        "",
    ]

    any_section = False
    for mem_type, heading in _EXPORT_SECTIONS:
        items = sorted(by_type.get(mem_type, []), key=lambda m: m.id)
        if not items:
            continue
        any_section = True
        lines.append(f"## {heading}")
        lines.append("")
        for mem in items:
            rel = _reference_for(mem, state_dir=state_dir)
            lines.append(f"@{rel}")
        lines.append("")

    if not any_section:
        lines.append("_(No accepted project memory yet.)_")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _reference_for(memory: Memory, *, state_dir: Path) -> str:
    """Return the export-relative ``../memories/<folder>/<id>.md`` path."""
    folder = MEMORY_TYPE_FOLDERS[memory.type]
    # The export lives at <state_dir>/exports/AGENTS.memory.md, so a memory at
    # <state_dir>/memories/<folder>/<id>.md is referenced as
    # ../memories/<folder>/<id>.md (POSIX separators).
    return f"../memories/{folder}/{memory.id}.md"


def write_export(
    memories: list[Memory],
    *,
    target: ExportTarget,
    output_path: Path,
    state_dir: Path,
) -> str:
    """Render and atomically write the export for the given target.

    Returns the rendered text. Raises ``ValueError`` for unknown targets.
    """
    if target != ExportTarget.agents_md:
        raise ValueError(f"Unsupported export target: {target}")
    text = render_export(memories, state_dir=state_dir)
    ensure_dir(output_path.parent)
    atomic_write_text(output_path, text)
    return text


__all__ = [
    "_EXPORT_SECTIONS",
    "accepted_project_memories",
    "render_export",
    "write_export",
]
